name: storage_element
version: 0.1.0
author: Keiichiro Ui <keiichiro.ui@gmail.com>
description: Custom elements to save or share text with URL hash fragments or localStrorage
homepage: https://kui.github.io/storage_element/
dependencies:
  archive: '>=1.0.0 <1.1.0'
  crypto: '>=0.9.0 <0.10.0'
  polymer: '>=0.11.0 <0.12.0'
dev_dependencies:
  ghpages_generator: '>=0.2.0 <0.3.0'
  path: '>=1.2.0 <1.3.0'
  unittest: '>=0.11.0 <0.12.0'
transformers:
- polymer:
    entry_points:
    - example/index.html
    - example/save-in-url-fragment.html
